theme: jekyll-theme-minimal
title: Code for Nashville Scooter Stories
description: Public interest analyses of scooters in Nashville (w/ open data and source code)
logo: logo.svg
show_downloads: "true"
# google_analytics: [Your Google Analytics tracking ID]
